Repository janson0004/well-worth-the-wait, pull requests merged in 2021-05, with the labels that each got.

#18 feat/restaurant-CRUD
  server/controllers/restaurant.js
  server/controllers/user.js
  server/index.js
  server/models/restaurant.js
  server/package-lock.json
  server/package.json
  server/routes/restaurant.js
Labels: feature

#24 refactor: color module, services module
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/components/GlobalStyle.jsx
  client/src/services/UserService.js
Labels: refactor

#23 build: setup environment
  README.md
  readme.txt
  server/package-lock.json
  server/populartimes_api.py
  server/requirements.txt
Labels: build, documentation

#28 feat: place view
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Chart.jsx
  client/src/components/Comment.jsx
  client/src/components/GlobalStyle.jsx
  client/src/views/Login.jsx
  client/src/views/Place.jsx
Labels: feature, fix

#30 Feat/merge login api
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Loader.jsx
  client/src/components/Navigation.jsx
  client/src/views/FavPlaces.jsx
  client/src/views/Home.jsx
  client/src/views/Login.jsx
Labels: feature

#29 feat: favplace view
  client/src/App.css
  client/src/App.jsx
  client/src/components/FavPlace.jsx
  client/src/components/Navigation.jsx
  client/src/index.css
  client/src/views/FavPlaces.jsx
Labels: feature

#32 feat: restaurants context
  client/src/App.jsx
  client/src/components/Loader.jsx
  client/src/components/Navigation.jsx
  client/src/contexts/RestaurantsContext.jsx
  client/src/index.jsx
  client/src/services/RestaurantsService.jsx
  client/src/services/UserService.jsx
  client/src/views/Login.jsx
  client/src/views/Place.jsx
Labels: feature, fix

#34 feat: popular-time
  server/controllers/restaurant.js
  server/routes/restaurant.js
Labels: feature

#36 fix: user info
  server/controllers/user.js
Labels: fix

#37 feat: dynamic content for single place
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Chart.jsx
  client/src/components/ReactAnimatedHeart.jsx
  client/src/services/RestaurantsService.jsx
  client/src/views/Place.jsx
Labels: feature

#39 feat: notmatch route
  client/src/App.jsx
  client/src/views/NotFound.jsx
  client/src/views/Place.jsx
Labels: fix

#40 fix: hot fix
  client/src/views/Place.jsx
Labels: fix

#41 feat: client comment system
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Comment.jsx
  client/src/services/RestaurantsService.jsx
  client/src/views/Place.jsx
  server/controllers/restaurant.js
  server/routes/restaurant.js
Labels: feature

#46 refactor: style nav and clean code
  .gitignore
  README.md
  client/src/App.jsx
  client/src/components/Chart.jsx
  client/src/components/GlobalStyle.jsx
  client/src/components/Navigation.jsx
  client/src/index.jsx
  client/src/views/Login.jsx
  client/src/views/Place.jsx
  readme.txt
  server/controllers/user.js
  server/requirements.txt
Labels: fix, refactor

#43 feat: fav place
  client/src/App.jsx
  client/src/components/FavPlace.jsx
  client/src/components/GlobalStyle.jsx
  client/src/views/FavPlaces.jsx
  client/src/views/Place.jsx
Labels: feature

#47 Fix/merge issue
  client/src/components/Navigation.jsx
  client/src/views/Home.jsx
  client/src/views/Place.jsx
  server/controllers/restaurant.js
Labels: fix

#49 feat: login-toast with error message
  client/package-lock.json
  client/package.json
  client/src/components/Navigation.jsx
  client/src/views/Login.jsx
Labels: style

#48 feat: search
  client/src/App.jsx
  client/src/views/Home.jsx
  client/src/views/Place.jsx
Labels: feature

#53 fix: user schema
  server/controllers/user.js
  server/models/user.js
Labels: fix

#54 Fix/hot fix
  client/src/App.jsx
  client/src/components/AdminPlace.jsx
  client/src/components/EditPlaceModal.jsx
  client/src/components/EditUserModal.jsx
  client/src/components/Users.jsx
  client/src/services/AdminService.jsx
  client/src/views/Place.jsx
  server/controllers/restaurant.js
  server/controllers/user.js
  server/routes/user.js
Labels: fix

#55 fix: hashing bug
  server/controllers/user.js
Labels: fix

#56 Fix/last fix
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/components/EditUserModal.jsx
  server/controllers/user.js
Labels: fix
